/*
Unique String hash value can be generated by using the hashing function,
i.e, by performing some arithmetic operations on it, in such a way that it produces 
unique values.
*/
#include<stdio.h>
#include<string.h>
#define mod 10000000007
int main(){
    char str[100];
    int prime1=2311,prime2=211;
    scanf("%[^\n]%*c", str);
    int length=strlen(str);
    int hash_value=0;
    for(int i=0;i<length;++i){
        hash_value+=((str[i])*prime1*prime2)%mod;
    }
    printf("%d",hash_value);
    return 0;
}